### ISSUE TITLE
question about the code

### ISSUE THREAD

**Issue by xianrui-luo** [TJCoding/Enhanced-Image-Colour-Transfer-2#3]
Hi, I am not familiar with C++,  and I am not sure if this is the case. In line 147 of the file main.cpp
> // Implement image refinements where a change is specified.
    SaturationProcessing(targetf, savedtf,
                         PercentSaturationShift/100.0);
    targetf=FullShading(targetf, savedtf, sourcef, ExtraShading,
                        PercentShadingShift/100.0);
    targetf=FinalAdjustment(targetf,savedtf,
                            PercentTint/100.0,
                            PercentModified/100.0);

Should the sentence be
>targetf=SaturationProcessing(targetf, savedtf,
                         PercentSaturationShift/100.0);

Maybe Saturationprocessing is not necessary, so it is written like this?

**Comment by TJCoding** [comment]
Yes, thank you.  I have corrected the code.  Before it didn't run saturation.  I am not sure how this happened because the web app at  https://www.dustfreesolutions.com/CT/CT.html seems to run correctly.   Looks like we picked up the error later but forgot to echo it back.

Well spotted and thank you!
