### ISSUE TITLE
Webapp errors out because of unset Content-Type header. 

### ISSUE THREAD

**Issue by metamaterialsuit** [TJCoding/Enhanced-Image-Colour-Transfer-2#5]
I had this program in both the most recent version of chrome and firefox. The issue is as shown in the console: The response containing CT_noLUT.wasm, initiated by a request from CT_noLUT.js, does not have a content-type header. When I manually specified "Content-Type: application/wasm",  as suggested by the console output, it worked. You can use chrome devtools to locally override response headers. 

Another thing you may want to note: at first, I was using jpg images that were around 5mb, and the application would crash. It seems the images need to be a smaller file size for the application to succeed. I don't know what is the root cause.

*edit: Just wanted to thank you guys for making both the software and the documentation available. It's been a big help in improving my understanding of color, color spaces, etc, and I wanted to say how appreciative I was. I've built my understanding of the relevant science/math based on the incredibly generous contributions of so many people to open source projects, free textbooks, and in general the relatively thankless enterprise of sharing knowledge. So thanks.  

_Originally posted by @metamaterialsuit in https://github.com/TJCoding/Enhanced-Image-Colour-Transfer-2/issues/2#issuecomment-1840129050_

**Comment by TJCoding** [comment]
Hi meta-m-s,

Thank you for raising this.

So, our web app has had some 27,000 hits and you are only the second person
to report a problem.  The first person to report a problem (See issue #2)
seemed to have an uncommon set up and the matter was resolved when he
resorted to a more usual set up.

This naturally leads to the question as to what your set up is and whether
it is unusual (either the software or the device or both).

I think you can see our dilemma.  We have some 50 people a day using the
Web App with a very low reported rate of issues.  The one thing we don’t
want to do is to update the software and inadvertently create a new issue
which would alienate would-be users.  So, we need to proceed very
cautiously.

I will alert my collaborator Michele Renzullo to look at this and see if he
can identify a solution which doesn’t represent a risk. In the meantime, if
you can provide more details that would be very helpful.

Regards

Terry Johnson

**Comment by TJCoding** [comment]
Hi meta-m-s,

*Large Image File Size.*

I have just run the following images with success on my desktop.

https://www.pexels.com/photo/aerial-photo-of-cityscape-at-night-2362004/

(11.3 MB   5242 x 6553)

https://upload.wikimedia.org/wikipedia/commons/archive/a/a7/20070209175249%21Sahara_satellite_hires.jpg

(8.31 Mb   7432 x 4168)



In both cases, I used the same image for Target and Palette and visually
checked that output was identical to the original.

The first of the above images took a while to process but otherwise there
was no issue.

For the second image, the image readily loaded as the Target but there was
some difficulty loading it as the Palette.  (I had to load a small image
first as a Palette and subsequently load the image I wanted.)

One thing to remember is that you only need high resolution for the Target
image.

Generally, I think the size of image that can be accommodated depends upon
the device you are using.  Different devices seem to reserve different
amounts of working storage.  I have an old phone which struggles with
moderate size images that my desktop can easily accommodate.

Regards

Terry Johnson

**Comment by metamaterialsuit** [comment]
Can you confirm that you are actually *not* seeing the console error? I wonder if the fact that you do not see a problem/no one else has reported an issue is because the fallback option succeeds for other people/you?
What version of chrome are you running? 

To reproduce: open chrome devtools, disable cache, view console output, ctrl-r to reload the page. 

Regarding my setup: It's just vanilla Ubuntu + chrome/firefox. Many people have reported the same issue.
See here: https://gist.github.com/WesThorburn/62ea13952749d6563ce2fb15b45f1ba8
here: https://stackoverflow.com/questions/62770223/incorrect-response-mime-type-expected-application-wasm-pspdfkit-and-the-reser
here: https://www.milanlaslop.dev/post/2020-01-03-webassembly-file-sending-correct-content-type/
Etc.

**Comment by TJCoding** [comment]
I have checked as you suggest (or at least as best I understand it).  I get two warnings rather than one error.  The first warning states that there is an unset content-type header.  The second states ‘falling back to Array buffer instantiation’.

I have little understanding or expertise in this field, hopefully Signore Renzullo will find time to look at it.   I am interested to see both Gmail and Github also give me errors/warnings.    I guessing that the sort of people who use Ubuntu are reasonably savvy computer users and will overcome any  obstacles that our web app presents.

**Comment by metamaterialsuit** [comment]
Yes, i hardly pretend to be a web dev, so unfortunately i can be of little help here. 
It seems the arraybuffer instantiation message refers to an alternate to the "streaming" instantiation available available in the WASM API
[STREAMING API](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming_static)

**Comment by TJCoding** [comment]
Try running this ....

https://www.dustfreesolutions.com/CT2/CT2

As far as I can tell, if I run this on my setup then no warnings are generated.

The CT2 folder is a copy of the CT folder except it contains an additional file.

The additional file is an .htaccess file which contains the single line 'AddType application/wasm .wasm'

I would be interested to learn if this works on your original set up (and any other set ups you are able to try).

If this looks good, then I have to somehow figure whether or not this fix could cause problems for most other users who currently have no issue.

**Comment by TJCoding** [comment]
I will ask Michele Renzullo to look at my proposed solution and to see whether he thinks there is any risk in implementing it.  In any case, I will not adopt the proposed change until the Jan 1.  Prior to then my access to computer facilities will be limited so I will wait until I am in a position where I could respond quickly if things went pear-shaped.

**Comment by TJCoding** [comment]
My proposed solution has been implemented for a number of days now with no negative feedback (nor any other feedback). On this basis I will close this issue.
