### ISSUE TITLE
Question: Is the point of the Ruderman color space NOT to decorrelate RGB values?

### ISSUE THREAD

**Issue by metamaterialsuit** [TJCoding/Enhanced-Image-Colour-Transfer-2#6]
After reading the Reinhard paper and looking into the Ruderman color space, I have noticed something that appears to be a contradiction. 
In your work, you say that correlation can be used to enhance the accuracy of the color transfer algorithm, but it seems like Reinhard et all specifically wanted to avoid correlation beween the color channels. 
Am I interpreting this correctly?

**Comment by TJCoding** [comment]
The Reinhard method (implicitly) assumes that, when the image is represented by 3 components, then there is no correlation between the components.   To 'help this assumption along' he tries to find a colour space representation where  this assumption is likely to be true.   Reinhard et al have observed that in the Ruderman colour space, for certain classes of natural imagery, there can be low dependency between the 3 components (when compared to other colour space representations).    The processing method presented here does not assume zero correlation between the two colour (alpha and beta) components of the Ruderman colour space.  Instead it measures the actual correlation in the palette image and applies a mathematical procedure to reproduce the same correlation in the output image.

In the case where the channels are actually uncorrelated the two methods should produce similar results but where there is correlation the method here should produce better results because it is makes a less restrictive assumption.  You can run the Web App in 'default' mode and in 'Reinhard'  mode to compare outcomes for an image pair of your choice.

**Comment by metamaterialsuit** [comment]
Ah, i see! Thank you for the explanation.

**Comment by TJCoding** [comment]
This issue appears to have been resolved.
